In [1]:
import numpy as np

In [2]:
np.stack(([1],[2]))

array([[1],
       [2]])

In [3]:
np.stack(([1],[2]), axis=1)

array([[1, 2]])

In [4]:
np.stack(([1],[2]), axis=-1)

array([[1, 2]])

In [ ]:
s12 = {0:[]}