In [2]:
import os
import datetime
print(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

import time
import glob
import tables as tb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from functools import reduce

2017-07-31 10:18:09


In [12]:
from   invisible_cities.types.ic_types_c import minmax
from   invisible_cities.evm.pmaps import Peak
from   invisible_cities.evm.event_model import  Voxel

In [6]:
r = np.random.randn(100,3)
H, edges = np.histogramdd(r, bins = (5, 8, 4))


In [8]:
edges

[array([-2.15886675, -1.27255926, -0.38625178,  0.5000557 ,  1.38636318,
         2.27267066]),
 array([-1.75615258, -1.06925372, -0.38235485,  0.30454401,  0.99144287,
         1.67834173,  2.36524059,  3.05213945,  3.73903831]),
 array([-2.6522876 , -1.25358422,  0.14511917,  1.54382256,  2.94252595])]

In [9]:
def centres(a : np.ndarray):
        return (a[1:] + a[:-1]) / 2

In [11]:
centres(np.array([10,10,10]))

array([ 10.,  10.])

In [ ]:
def neighbours(va : Voxel, vb : Voxel):
    return ((abs(va.pos - vb.pos) / voxel_dimensions) < 1.5).all()


In [5]:
vox_size = np.array([10,10,10],dtype=np.int16)  
bounding_box(vox_size)

AttributeError: 'numpy.int16' object has no attribute 'pos'